### ISSUE TITLE
"print" call in README has two p's

### ISSUE THREAD

**Issue by DGKSK8LIFE** [Giphy/giphy-python-client#2]

**Comment by DGKSK8LIFE** [comment]
![image](https://user-images.githubusercontent.com/45473363/89553011-94562900-d7d2-11ea-982b-4bcceda6d60d.png)

**Comment by Brodan** [comment]
Hey @DGKSK8LIFE, this is not by mistake. Notice at the top of this code snippet is: `from pprint import pprint`

This is calling Python's [pprint](https://docs.python.org/3/library/pprint.html) (also known as pretty-print) module. pprint is used to make blocks of text like this `api_response` more readable.

**Comment by DGKSK8LIFE** [comment]
ah ok; my bad; tysm @Brodan
